# Generated by Django 5.0.3 on 2024-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataresultados',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
